### ISSUE TITLE
Confused as to what this brings to the table that languageserver does not?

### ISSUE THREAD

**Issue by emilBeBri** [jalvesaq/cmp-nvim-r#4]
I'm sorry it's not really a bug, but perhaps the readme could explain? I'm guessing you didn't spend time making this just for the exercise, and I'm a big fan of nvim-R, so I'm thinking there might be some benefit that is not clear from the description?

**Comment by jalvesaq** [comment]
I would not have made Nvim-R if RStudio existed in 2009. If I were starting to use R now, even if unsatisfied with RStudio, I would not make Nvim-R because the languageserver is good enough. But since Nvim-R is already there, I can see that it has some advantages:

- Object Browser.
- Highlighting function names when their libraries are loaded.
- Completion of objects from R's workspace, including column names of data.frames with a preview of the variable's `summary()` or `str()`.
- The completion of arguments of generic functions, at least sometimes, correctly guess what the specific function is being used.
- Less CPU and RAM usage: the languageserver keeps running many R instances in parallel while Nvim-R mostly runs just a tiny C application, the `nclientserver`.

**Comment by emilBeBri** [comment]
well thank God it didn't, then - I really don't like Rstudio and I love nvim-R! 

thank you for the clarification
